/* eslint-disable spaced-comment, object-curly-spacing */

// import * as Corelib from './red/esm/stdlib/corelib-esm.js'

export {Corelib, Store, DOMplusUltra} from 'https://rez.mork.work/proxy-wa.js'
export { CT } from './red/esm/stdlib/contest-esm.js'

export { onReady as onWaapiReady } from './wautils.js'
export { createBeeDebug } from './beefx-debug.js'
export * as beeCommon from './beefx-common.js'
export { BeeFX } from './beefx.js'

import './fxs/beefxs-basic.js'
import './fxs/beefxs-tinnitus.js'
import './fxs/beefxs-ratio.js'
import './fxs/beefxs-amp.js'
import './fxs/beefxs-equalizer.js'
import './fxs/beefxs-delays.js'
import './fxs/beefxs-noise.js'
import './fxs/beefxs-reverb.js'
import './fxs/beefxs-dattorro-reverb.js'
import './fxs/beefxs-compressor.js'
import './fxs/beefxs-wobble.js'
import './fxs/beefxs-scrlfo.js'
import './fxs/beefxs-chorus.js'
import './fxs/beefxs-pitchshifter.js'
import './fxs/beefxs-osc.js'
import './fxs/beefxs-env.js'
import './fxs/beefxs-overdrive.js'
export * as Chebyshev from './fxs/chebyshev-math.js'
import './fxs/beefxs-iir.js'
import './fxs/beefxs-ringmod.js'

export { detectBPMj } from './med/bpmj-esm.js'
export * as BPM from './med/bpm-auditor-esm.js'

import './ext/beext-oscillator.js'
import './ext/beext-oscilloscope.js'
import './ext/beext-spectrum.js'
import './ext/beext-spectra.js'
import './ext/beext-recmulti.js'
import './med/beefxs-bpmtrans-esm.js'

export * from './vis/graphbase.js'
export * from './vis/extend-canvas.js'
export * as Visualizer from './vis/visualizer.js'
export * from './vis/gr-compressor.js'
export * from './vis/gr-audiobuffer.js'
export * from './vis/gr-freq.js'
export * from './vis/gr-sigmoid.js'
